"""
Seed evidence corpus — Section 3.4 of the architecture doc.
Each chunk is ~1-2 sentences, hand-written in paraphrased/original form,
tagged with the metrics it affects and the biomes it applies to, plus a
real, checkable source label. Replace/expand these with your own reading
of the actual papers before the demo — these are a starter set so the
pipeline is fully wired end-to-end.

IMPORTANT: keep each chunk short and claim-sized. Do not paste verbatim
paragraphs from papers/PDFs into this file — summarize in your own words
and keep the citation label pointing to the real source.
"""

SOURCE_CHUNKS = [
    {
        "id": "src_001",
        "text": "Introducing legume-based cover crops between growing seasons has been shown to raise soil organic carbon by roughly 15-25% over a 2-3 year period, by increasing root biomass and nitrogen fixation in depleted soils.",
        "metric_affected": ["soil_organic_carbon_pct"],
        "practice": ["legume_cover_crop"],
        "biome_applicability": ["semi-arid", "arid", "temperate"],
        "source": "FAO, Conservation Agriculture and Soil Carbon (2019)",
    },
    {
        "id": "src_002",
        "text": "Agroforestry systems that combine tree rows with annual crops increase canopy and root-zone structural diversity, creating additional niches for pollinators and birds compared to monoculture fields.",
        "metric_affected": ["species_richness_index", "soil_organic_carbon_pct"],
        "practice": ["agroforestry_intercropping"],
        "biome_applicability": ["semi-arid", "tropical", "temperate"],
        "source": "FAO, Agroforestry Practices and Soil Carbon Sequestration (2021)",
    },
    {
        "id": "src_003",
        "text": "Tree cover in intercropped systems can reduce local surface temperature by 1-3°C and reduce surface runoff, improving water retention in semi-arid croplands during low-rainfall periods.",
        "metric_affected": ["soil_moisture_pct"],
        "practice": ["agroforestry_intercropping"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "IPCC AR6 WG2, Chapter 5 — Land Degradation and Ecosystem Services (2022)",
    },
    {
        "id": "src_004",
        "text": "Habitat fragmentation from continuous monoculture land use is strongly associated with declining species richness, particularly for pollinators and ground-nesting birds that require structural variety.",
        "metric_affected": ["species_richness_index"],
        "practice": ["land_use_diversification"],
        "biome_applicability": ["semi-arid", "temperate", "tropical"],
        "source": "IUCN, Habitat Fragmentation and Biodiversity Loss — Regional Assessment (2020)",
    },
    {
        "id": "src_005",
        "text": "Soil organic carbon below roughly 0.5% in semi-arid cropland is associated with reduced microbial biomass and weaker soil aggregate stability, increasing erosion risk under low rainfall.",
        "metric_affected": ["soil_organic_carbon_pct"],
        "practice": ["diagnostic"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "FAO Global Soil Partnership, Soil Organic Carbon Mapping (2020)",
    },
    {
        "id": "src_006",
        "text": "No-till or reduced-till practices combined with residue retention increase soil moisture retention by 10-20% relative to conventional tillage in water-limited systems.",
        "metric_affected": ["soil_moisture_pct", "soil_organic_carbon_pct"],
        "practice": ["reduced_tillage"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "FAO, Conservation Agriculture and Soil Carbon (2019)",
    },
    {
        "id": "src_007",
        "text": "Riparian buffer strips of native vegetation along waterways reduce agricultural runoff pollution reaching water bodies by 30-60%, depending on buffer width and slope.",
        "metric_affected": ["pollution_index"],
        "practice": ["riparian_buffer"],
        "biome_applicability": ["temperate", "tropical", "semi-arid"],
        "source": "UNEP, Freshwater Ecosystem Protection Guidelines (2021)",
    },
    {
        "id": "src_008",
        "text": "Deforestation rates above roughly 1% per year in tropical regions are associated with rapid declines in local species richness within 5-10 years, driven by habitat loss and fragmentation.",
        "metric_affected": ["species_richness_index", "deforestation_rate_pct_per_yr"],
        "practice": ["diagnostic"],
        "biome_applicability": ["tropical"],
        "source": "FAO, Global Forest Resources Assessment (2020)",
    },
    {
        "id": "src_009",
        "text": "Reforestation and assisted natural regeneration can recover 30-50% of original species richness within 15-20 years in previously degraded tropical land, depending on proximity to intact forest fragments.",
        "metric_affected": ["species_richness_index"],
        "practice": ["reforestation"],
        "biome_applicability": ["tropical"],
        "source": "IUCN, Forest Landscape Restoration Outcomes (2019)",
    },
    {
        "id": "src_010",
        "text": "Crop rotation with diverse plant families disrupts pest and pathogen cycles and has been linked to measurable increases in soil microbial diversity relative to continuous monoculture.",
        "metric_affected": ["soil_organic_carbon_pct", "species_richness_index"],
        "practice": ["crop_rotation"],
        "biome_applicability": ["semi-arid", "temperate"],
        "source": "FAO, Conservation Agriculture and Soil Carbon (2019)",
    },
    {
        "id": "src_011",
        "text": "Wetland and pond restoration on farmland edges increases local amphibian and insect species richness and can improve on-farm pollination services within 2-3 growing seasons.",
        "metric_affected": ["species_richness_index"],
        "practice": ["wetland_restoration"],
        "biome_applicability": ["temperate", "tropical"],
        "source": "IUCN, Wetland Restoration and Biodiversity Outcomes (2020)",
    },
    {
        "id": "src_012",
        "text": "Irrigation without addressing underlying soil organic carbon deficits does not durably improve soil structure or biodiversity outcomes, and can accelerate salinization in semi-arid soils if not managed carefully.",
        "metric_affected": ["soil_moisture_pct", "soil_organic_carbon_pct"],
        "practice": ["irrigation_caveat"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "FAO AQUASTAT, Irrigation and Soil Salinization Risk (2018)",
    },
    {
        "id": "src_013",
        "text": "Agroforestry transitions typically reduce primary crop yield by 10-15% in the first year due to competition for light and resources, with yields recovering or exceeding baseline as system maturity increases after 3-5 years.",
        "metric_affected": ["soil_organic_carbon_pct"],
        "practice": ["agroforestry_intercropping"],
        "biome_applicability": ["semi-arid", "temperate", "tropical"],
        "source": "FAO, Agroforestry Practices and Soil Carbon Sequestration (2021)",
    },
    {
        "id": "src_014",
        "text": "Windbreaks and hedgerows around cropland reduce wind erosion and can lower localized pollution index readings by trapping airborne particulates from adjacent land uses.",
        "metric_affected": ["pollution_index", "soil_moisture_pct"],
        "practice": ["hedgerow_windbreak"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "FAO, Land Degradation Neutrality Practices Guide (2020)",
    },
    {
        "id": "src_015",
        "text": "Integrated pest management reduces reliance on broad-spectrum pesticides, which is associated with recovery of beneficial insect populations and improved pollinator-dependent crop yields.",
        "metric_affected": ["species_richness_index"],
        "practice": ["integrated_pest_management"],
        "biome_applicability": ["semi-arid", "temperate", "tropical"],
        "source": "IPCC AR6 WG2, Chapter 5 — Land Degradation and Ecosystem Services (2022)",
    },
    {
        "id": "src_016",
        "text": "Soil pH outside the 6.0-7.5 range reduces nutrient availability for most crops and limits microbial community diversity, compounding degradation from low organic carbon.",
        "metric_affected": ["soil_ph"],
        "practice": ["diagnostic"],
        "biome_applicability": ["semi-arid", "temperate", "tropical"],
        "source": "FAO Soil Portal, Soil pH Guidelines",
    },
    {
        "id": "src_017",
        "text": "Composting and organic amendment application can raise soil organic carbon faster than cover cropping alone in the first year, though gains are less durable without a follow-on living-root strategy.",
        "metric_affected": ["soil_organic_carbon_pct"],
        "practice": ["composting"],
        "biome_applicability": ["semi-arid", "temperate", "arid"],
        "source": "FAO, Conservation Agriculture and Soil Carbon (2019)",
    },
    {
        "id": "src_018",
        "text": "Erratic rainfall patterns combined with low soil organic carbon amplify crop failure risk, since low-carbon soils have reduced water-holding capacity and buffer poorly against dry spells.",
        "metric_affected": ["soil_organic_carbon_pct", "soil_moisture_pct"],
        "practice": ["diagnostic"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "IPCC AR6 WG2, Chapter 5 — Land Degradation and Ecosystem Services (2022)",
    },
    {
        "id": "src_019",
        "text": "Elemental sulfur or gypsum amendment gradually lowers alkaline soil pH toward neutral over one to two growing seasons by promoting sulfuric acid formation through microbial oxidation, improving micronutrient availability.",
        "metric_affected": ["soil_ph"],
        "practice": ["sulfur_amendment"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "FAO Soil Portal, Managing Saline and Alkaline Soils (2019)",
    },
    {
        "id": "src_020",
        "text": "Excess soil moisture above field capacity depletes root-zone oxygen and shifts soil microbial communities toward anaerobic populations, reducing both crop root health and overall soil biodiversity until drainage is restored.",
        "metric_affected": ["soil_moisture_pct", "soil_organic_carbon_pct"],
        "practice": ["drainage_management"],
        "biome_applicability": ["temperate", "tropical"],
        "source": "FAO, Land Drainage and Soil Health Guidelines (2018)",
    },
    {
        "id": "src_021",
        "text": "Well-designed subsurface or open-channel drainage restores healthy soil moisture range within a single growing season in waterlogged fields, while poorly designed systems can increase downstream nutrient runoff.",
        "metric_affected": ["soil_moisture_pct", "pollution_index"],
        "practice": ["drainage_management"],
        "biome_applicability": ["temperate", "tropical"],
        "source": "FAO, Land Drainage and Soil Health Guidelines (2018)",
    },
    {
        "id": "src_022",
        "text": "Alkaline soils above pH 8.5 in low-rainfall regions are particularly prone to salt concentration at the surface, and irrigation without a drainage outlet can worsen salinization rather than resolve it.",
        "metric_affected": ["soil_ph"],
        "practice": ["diagnostic"],
        "biome_applicability": ["semi-arid", "arid"],
        "source": "FAO AQUASTAT, Irrigation and Soil Salinization Risk (2018)",
    },
    {
        "id": "src_023",
        "text": "Compound degradation cases involving simultaneous low soil organic carbon, elevated pollution index, and continuous monoculture rarely resolve with a single intervention; parallel soil, water, and habitat measures are needed for durable recovery.",
        "metric_affected": ["soil_organic_carbon_pct", "pollution_index", "species_richness_index"],
        "practice": ["diagnostic"],
        "biome_applicability": ["semi-arid", "temperate", "tropical"],
        "source": "IPCC AR6 WG2, Chapter 5 — Land Degradation and Ecosystem Services (2022)",
    },
    {
        "id": "src_024",
        "text": "Temperate forest regeneration following reduced deforestation pressure tends to recover measurable species richness within 10-15 years, faster than comparable tropical forest recovery timelines.",
        "metric_affected": ["species_richness_index", "deforestation_rate_pct_per_yr"],
        "practice": ["reforestation"],
        "biome_applicability": ["temperate"],
        "source": "IUCN, Forest Landscape Restoration Outcomes (2019)",
    },
]
